---
instances:
  master.example.demo:
    platform: centos7_master
    flavor: m1.large

  centos7a.example.demo:
    platform: centos7

  debian1.example.demo:
    platform: debian8

  gitlab.example.demo:
    platform: centos7
    flavor: d1.medium

  git-runner.example.demo:
    platform: centos7

  server2012r2a.example.demo:
    platform: server2012
    flavor: d1.medium

  server2012r2b.example.demo:
    platform: server2012
    flavor: d1.medium

  jenkins.example.demo:
    platform: centos6
