userdata:
  windows: |
    <powershell>
    net user Administrator "Password1"
    wmic useraccount where "name='Administrator'" set PasswordExpires=FALSE

    # Enable RDP
    set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    netsh advfirewall firewall add rule name="RDP 3389" dir=in localport=3389 protocol=TCP action=allow

    # Enable WinRM
    winrm quickconfig -q
    winrm set winrm/config/winrs '@{MaxMemoryPerShellMB="0"}'
    winrm set winrm/config '@{MaxTimeoutms="7200000"}'
    winrm set winrm/config/service '@{AllowUnencrypted="true"}'
    winrm set winrm/config/service/auth '@{Basic="true"}'

    netsh advfirewall firewall add rule name="WinRM 5985" protocol=TCP dir=in localport=5985 action=allow

    net stop winrm
    sc.exe config winrm start=auto
    net start winrm

    # turn off PowerShell execution policy restrictions
    Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope LocalMachine
    </powershell>

  centos: |
    #!/bin/bash
    sed -i 's/Defaults    requiretty//g' /etc/sudoers
    grep 'SELINUX\=disabled' /etc/selinux/config
    if [ $? -ne 0 ]; then
    echo '
    SELINUX=disabled
    SELINUXTYPE=targeted
    ' > /etc/selinux/config
    setenforce Permissive
    echo 'SELinux is now PERMISSIVE, but you need to reboot to fully disable'
    fi

    yum clean all
    yum install -y curl

  debian: |
    #!/bin/bash
    sed -i 's/Defaults    requiretty//g' /etc/sudoers
    apt-get update
    apt-get install -y curl

  ubuntu: |
    #!/bin/bash
    sed -i 's/Defaults    requiretty//g' /etc/sudoers
    apt-get update
    apt-get install -y curl

