---
defaults:
  ssh_username: 
  openstack_auth_url:
  username: 
  password: 
  tenant_name: 
  keypair_name: 
  private_key_path: 
  communicator: 
  ssh_disabled: 
  winrm_username: 
  winrm_password: 
  master_ip: 
instance_defaults:
  flavor: 
  floating_ip_pool: 
  networks:
    - network
  security_groups:
    - default
  box: 'dummy'
  sync_method: none
  roles:
    - dummy
instances:
  example.example.demo:
    primary: false
    autoup: true
    image: centos_7_x86_64
    roles:
      - linux_hosts
      - disable_selinux
      - puppet_master
    sync_method: rsync
    flavor: big
